[workspace]
members = [
    "duvet",
    "duvet-core",
    "duvet-core/examples/line-count"
]

[profile.release]
lto = true
codegen-units = 1
incremental = false

[profile.bench]
lto = true
codegen-units = 1
incremental = false
