[package]
name = "duvet"
version = "0.1.0"
authors = ["Cameron Bytheway <bytheway.cameron@gmail.com>"]
description = "Rich code coverage"
license = "MIT"
edition = "2018"

[dependencies]
anyhow = "1"
rustc-demangle = "0.1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serde_tuple = "0.5"

[dev-dependencies]
bolero = "0.6"
