[package]
name = "duvet"
version = "0.1.0"
authors = ["Cameron Bytheway <bytheway.cameron@gmail.com>"]
description = "Rich code coverage"
license = "MIT"
edition = "2018"

[features]
default = ["llvm-coverage"]
llvm-coverage = ["rustc-demangle", "serde", "serde_json", "serde_tuple"]

[dependencies]
anyhow = "1"
hash_hasher = "2"
rusqlite = { version = "0.24", features = ["bundled"] }
rustc-demangle = { version = "0.1", optional = true }
serde = { version = "1", features = ["derive"], optional = true }
serde_json = { version = "1", optional = true }
serde_tuple = { version = "0.5", optional = true }
sha2 = "0.9"
smallvec = "1"

[dev-dependencies]
bolero = "0.6"
